"""make unique field in payment category model

Revision ID: 09b356cf5bba
Revises: f85512824d1a
Create Date: 2025-03-13 11:40:58.262229

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09b356cf5bba"
down_revision: Union[str, None] = "f85512824d1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "paymentcategory", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "paymentcategory", type_="unique")
    # ### end Alembic commands ###
