"""add user_id to payment model

Revision ID: 48f58d545e0a
Revises: 56b0ac053489
Create Date: 2025-03-19 18:47:18.354986

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48f58d545e0a"
down_revision: Union[str, None] = "56b0ac053489"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payment", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "payment", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment", type_="foreignkey")
    op.drop_column("payment", "user_id")
    # ### end Alembic commands ###
