"""add user id to payment method

Revision ID: 76f8f06aaa9e
Revises: 0b8825627df6
Create Date: 2025-03-16 17:37:54.701047

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76f8f06aaa9e"
down_revision: Union[str, None] = "0b8825627df6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("paymentmethod", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_foreign_key(None, "paymentmethod", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "paymentmethod", type_="foreignkey")
    op.drop_column("paymentmethod", "user_id")
    # ### end Alembic commands ###
