"""email field in user model now is nullable

Revision ID: bfa8e8bba393
Revises: 48f58d545e0a
Create Date: 2025-03-20 20:56:39.936342

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bfa8e8bba393"
down_revision: Union[str, None] = "48f58d545e0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
