services:
  finance_api:
    build:
      dockerfile: Dockerfile
      context: ./api
    container_name: api
    env_file:
      - api/src/.env
    restart: always
    networks:
      - finance_api_network
    volumes:
      - ./api/src:/opt/app/src
      - ./api/logs/:/var/log/app/
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    container_name: nginx
    build:
      context: ./nginx/.
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./nginx/logs/:/var/log/nginx/
    depends_on:
      - finance_api
    ports:
      - "80:80"
    networks:
      - finance_api_network

  postgres:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    env_file: api/src/.env
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - finance_api_network

networks:
  finance_api_network:

volumes:
  postgres_data:
